/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SkzBadge {
        "color": string;
        "variant": 'pill' | 'label' | 'bubble';
    }
    interface SkzToggle {
        "toggleId": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSkzBadgeElement extends Components.SkzBadge, HTMLStencilElement {
    }
    var HTMLSkzBadgeElement: {
        prototype: HTMLSkzBadgeElement;
        new (): HTMLSkzBadgeElement;
    };
    interface HTMLSkzToggleElement extends Components.SkzToggle, HTMLStencilElement {
    }
    var HTMLSkzToggleElement: {
        prototype: HTMLSkzToggleElement;
        new (): HTMLSkzToggleElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "skz-badge": HTMLSkzBadgeElement;
        "skz-toggle": HTMLSkzToggleElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SkzBadge {
        "color"?: string;
        "variant"?: 'pill' | 'label' | 'bubble';
    }
    interface SkzToggle {
        "onChanged"?: (event: CustomEvent<boolean>) => void;
        "toggleId"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "skz-badge": SkzBadge;
        "skz-toggle": SkzToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "skz-badge": LocalJSX.SkzBadge & JSXBase.HTMLAttributes<HTMLSkzBadgeElement>;
            "skz-toggle": LocalJSX.SkzToggle & JSXBase.HTMLAttributes<HTMLSkzToggleElement>;
        }
    }
}
